batch_size: 1
world_size: 1
model: vit_large_patch16
epochs: 1
blr: 5e-3
layer_decay: 0.65
weight_decay: 0.05
drop_path: 0.2
nb_classes: 2
data_path: dataset
task: finetune_IDRiD
finetune: RETFound_cfp_weights.pth
input_size: 224
