eval: true
batch_size: 64
world_size: 4
model: vit_large_patch16
nb_classes: 2
data_path: /mnt/data/Anastasiia_Ponkratova/RETFound_MAE/datasets/REFUGE2/
task: ./results/finetune_REFUGE2/ # specifies the folder for evaluation logs
resume: ./results/finetune_REFUGE2/checkpoint-best.pth
input_size: 224
pin_mem: True
num_workers: 24
