eval: true
batch_size: 16
world_size: 4
model: vit_large_patch16
nb_classes: 8
data_path: ./datasets/ODIR/
task: ./results/finetune_ODIR/  # specifies the folder for evaluation logs
resume: ./results/finetune_ODIR/checkpoint-best.pth
input_size: 224
pin_mem: True
num_workers: 24
