eval: true
batch_size: 64
world_size: 4
model: vit_large_patch16
nb_classes: 2
data_path: /mnt/data/cfi_manual_diabetes_0.1/
task: ./results/finetune_cfi_manual_diabetes_0.1/  # specifies the folder for evaluation logs
resume: ./results/finetune_cfi_manual_diabetes_0.1/checkpoint-best.pth
input_size: 224
pin_mem: True
num_workers: 24
