eval: true
batch_size: 16
world_size: 1
model: vit_large_patch16
epochs: 50
blr: 5e-3
layer_decay: 0.65
weight_decay: 0.05
drop_path: 0.2
nb_classes: 5
data_path: IDRiD_data
task: internal_IDRiD
resume: finetune_IDRiD/checkpoint-best.pth
input_size: 224
