batch_size: 16
accum_iter: 1
model: vit_large_patch16
blr: 2.0e-4
layer_decay: 0.9
weight_decay: 0.005
epochs: 50
warmup_epochs: 3
drop_path: 0.3
smoothing: 0.0
color_jitter: 0.3
aa: 'rand-m9-mstd0.5-inc1'
reprob: 0.2
mixup: 0.0
cutmix: 0.0
mixup_prodb: 0.0
mixup_mode: 'batch'
nb_classes: 2
input_size: 224
num_workers: 24
world_size: 1
pin_mem: True
data_path: /mnt/data/Anastasiia_Ponkratova/RETFound_MAE/datasets/REFUGE2/
task: ./results/finetune_REFUGE2/
finetune: ./RETFound_cfp_weights.pth




