batch_size: 64
accum_iter: 2
model: vit_large_patch16
blr: 3.0e-4
layer_decay: 0.75
weight_decay: 0.05
epochs: 80
warmup_epochs: 5
drop_path: 0.2
smoothing: 0.05
color_jitter: 0.4
aa: 'rand-m15-mstd0.8-inc1'
reprob: 0.3
mixup: 0.3
cutmix: 0.3
mixup_prob: 0.3
mixup_mode: 'batch'
nb_classes: 2
input_size: 224
num_workers: 24
world_size: 1
pin_mem: True
data_path: /mnt/data/cfi_manual_hypertension_strict/
task: ./results/finetune_cfi_manual_hypertension_strict/
finetune: ./RETFound_cfp_weights.pth
