batch_size: 64
accum_iter: 4
model: vit_large_patch16
blr: 2.0e-4
layer_decay: 0.85
weight_decay: 0.15
epochs: 80
warmup_epochs: 5
drop_path: 0.1
smoothing: 0.05
color_jitter: 0.2
aa: 'rand-m9-mstd0.5-inc1'
reprob: 0.1
mixup: 0.0
cutmix: 0.0
mixup_prob: 0.0
mixup_mode: 'batch'
nb_classes: 2
input_size: 224
num_workers: 24
world_size: 1
pin_mem: True
data_path: /mnt/data/cfi_manual_hypertension_AHA/
task: ./results/finetune_cfi_manual_hypertension_AHA_top/
resume: ./results/finetune_cfi_manual_hypertension_AHA_top/checkpoint-best.pth
finetune: ./RETFound_cfp_weights.pth
