batch_size: 16
world_size: 1
model: vit_large_patch16
epochs: 50
blr: 5e-3
layer_decay: 0.65
weight_decay: 0.05
drop_path: 0.2
nb_classes: 2
data_path: origa
task: finetune_IDRiD  # specifies the folder for logs and checkpoints
finetune: RETFound_cfp_weights.pth  # RETFound pre-trained weights for colour fundus image
input_size: 224

