batch_size: 64
accum_iter: 4
model: vit_large_patch16
blr: 3.4e-4
layer_decay: 0.8
weight_decay: 0.03
epochs: 50
warmup_epochs: 3
drop_path: 0.1
smoothing: 0.0
color_jitter: 0.2
aa: 'rand-m9-mstd0.5-inc1'
reprob: 0.05
mixup: 0.0
cutmix: 0.0
mixup_prob: 0.0
mixup_mode: ''
nb_classes: 2
input_size: 224
num_workers: 24
world_size: 1
pin_mem: True
data_path: /mnt/data/cfi_manual_strong/
task: ./results/finetune_cfi_manual_strong/
finetune: ./RETFound_cfp_weights.pth
