batch_size: 64
accum_iter: 4
model: vit_large_patch16
blr: 2.5e-4
layer_decay: 0.8
weight_decay: 0.1
epochs: 150
warmup_epochs: 10
drop_path: 0.3
smoothing: 0.0
color_jitter: 0.4
aa: 'rand-m15-mstd0.8-inc1'
reprob: 0.2
mixup: 0.0
cutmix: 0.0
mixup_prob: 0.0
mixup_mode: ''
nb_classes: 2
input_size: 224
num_workers: 24
world_size: 1
pin_mem: True
data_path: /mnt/data/cfi_manual_diabetes/
task: ./results/finetune_cfi_manual_diabetes/
finetune: ./RETFound_cfp_weights.pth
