batch_size: 64
accum_iter: 4
model: vit_large_patch16
blr: 2.5e-4
layer_decay: 0.8
weight_decay: 0.05
epochs: 80
warmup_epochs: 5
drop_path: 0.2
smoothing: 0.0
color_jitter: 0.1
aa: 'v0'
reprob: 0.0
mixup: 0.05
cutmix: 0.05
mixup_prob: 0.3
mixup_mode: 'batch'
nb_classes: 2
input_size: 224
num_workers: 24
world_size: 1
pin_mem: True
data_path: /mnt/data/cfi_manual_diabetes_0.1/
task: ./results/finetune_cfi_manual_diabetes_0.1/
finetune: ./RETFound_cfp_weights.pth
