batch_size: 16
accum_iter: 2
model: vit_large_patch16
blr: 5e-4
layer_decay: 0.65
weight_decay: 0.01
epochs: 30
warmup_epochs: 5
drop_path: 0.2
smoothing: 0.1
color_jitter: 0.1
aa: 'v0'
reprob: 0.1
mixup: 0.5
cutmix: 0.5
mixup_prob: 0.5
mixup_mode: 'batch'
nb_classes: 8
input_size: 224
num_workers: 8
world_size: 1
pin_mem: True
data_path: ./datasets/ODIR/
task: ./finetune_ODIR/  # specifies the folder for logs and checkpoints
finetune: ./RETFound_cfp_weights.pth  # RETFound pre-trained weights for colour fundus image
