batch_size: 512
accum_iter: 1
model: vit_large_patch16
blr: 2.5e-4
layer_decay: 0.75
weight_decay: 0.02
epochs: 50
warmup_epochs: 10
drop_path: 0.4
smoothing: 0.1
color_jitter: 0.05
aa: 'v0'
reprob: 0.0
mixup: 0.2
cutmix: 0.2
mixup_prob: 0.5
mixup_mode: 'batch'
nb_classes: 8
input_size: 224
num_workers: 16
world_size: 1
pin_mem: True
data_path: ./datasets/ODIR/
task: ./results/finetune_ODIR/  # specifies the folder for logs and checkpoints
finetune: ./RETFound_cfp_weights.pth  # RETFound pre-trained weights for colour fundus image
