eval: true
batch_size: 64
world_size: 4
model: vit_large_patch16
nb_classes: 2
data_path: /mnt/data/Anastasiia_Ponkratova/RETFound_MAE/datasets/Kaggle/
task: ./results/finetune_Kaggle/
resume: ./results/finetune_Kaggle/checkpoint-best.pth
input_size: 224
pin_mem: True
num_workers: 24
